#!/bin/bash


#Source params file
source /home/detoeuf/Manuel/scripts/2014-08-02/config/params

cd $DATA_LOCATION


#Variables
recipe=muse_standard
filesof=standard.sof
#patterns=(OBJECT WFM-NOAO-N )  #Patterns to seach in the mastersof. Be careful it needs to be in the right order. The patterns are output of the Python program seetype.py
#numsof=7 


#a=`echo ${patterns[*]/%/.*} | rev | cut -c 3- | rev`
a=0001 #Exposure to process. 
> $filesof
for i in `ls PIXTABLE_STD*$a*.fits`
do 
	echo `readlink -f $i` PIXTABLE_OBJECT >> $filesof
done



# Using all the cal from the program or download online for this science verification run
echo $CALIB_FILES/extinct_table.fits EXTINCT_TABLE   >> $filesof
echo $CALIB_FILES/std_fulx_table.fits
echo $CALIB_FILES/filter_list.fits FILTER_LIST   >> $filesof




taskset -c 0-23 esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof
