#!/bin/bash

#It creates the sof for the master wavecal
# then execute the command to do the wavelenght calibrationa. Need to create filearc using the python script arc.py. 

#Source params file
source /home/detoeuf/Manuel/scripts/2014-08-02/config/params

cd $DATA_LOCATION


#Variables
recipe=muse_twilight
filesof=twilight.sof
patterns=(SKYFLAT WFM-NOAO-N )  #Patterns to seach in the mastersof. Be careful it needs to be in the right order. The patterns are output of the Python program seetype.py
numsof=7


a=`echo ${patterns[*]/%/.*} | rev | cut -c 3- | rev`
cat mastersof.txt | grep -Ew "$a" | head -n $numsof > $filesof

echo $ESOREX_OUTPUT_DIR/MASTER_BIAS.fits MASTER_BIAS >> $filesof
echo $ESOREX_OUTPUT_DIR/MASTER_FLAT.fits MASTER_FLAT >> $filesof
echo $CALIB_FILES/badpix_table.fits BADPIX_TABLE >> $filesof
echo $ESOREX_OUTPUT_DIR/TRACE_TABLE.fits TRACE_TABLE >> $filesof
echo $ESOREX_OUTPUT_DIR/WAVECAL_TABLE.fits WAVECAL_TABLE >> $filesof

taskset -c 0-23 esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof
