#!/bin/bash


#Source params file
source /home/detoeuf/Manuel/scripts/2014-08-02/config/params

cd $DATA_LOCATION


#Variables
recipe=muse_scibasic
filesof=scibasicobject.sof
patterns=(OBJECT WFM-NOAO-N )  #Patterns to seach in the mastersof. Be careful it needs to be in the right order. The patterns are output of the Python program seetype.py
#numsof=7 #Check this


a=`echo ${patterns[*]/%/.*} | rev | cut -c 3- | rev`
cat cleanmastersof.txt | grep -Ew "$a"  $numsof > $filesof
cat cleanmastersof.txt | grep ILLUM >> $filesof

echo $ESOREX_OUTPUT_DIR/TWILIGHT_CUBE.fits TWILIGHT_CUBE >> $filesof
echo $ESOREX_OUTPUT_DIR/MASTER_BIAS.fits MASTER_BIAS >> $filesof
echo $ESOREX_OUTPUT_DIR/MASTER_FLAT.fits MASTER_FLAT >> $filesof
echo $ESOREX_OUTPUT_DIR/TRACE_TABLE.fits TRACE_TABLE >> $filesof
echo $ESOREX_OUTPUT_DIR/WAVECAL_TABLE.fits WAVECAL_TABLE >> $filesof
echo $CALIB_FILES/geometry_table_wfm_comm2b.fits GEOMETRY_TABLE >> $filesof
echo $CALIB_FILES/badpix_table.fits BADPIX_TABLE >> $filesof


taskset -c 0-23 esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof
