#!/bin/bash


#Source params file
source /home/detoeuf/Manuel/scripts/2014-08-02/config/params

cd $DATA_LOCATION


#Variables
recipe=muse_scipost
filesof=scipost.sof
#patterns=(OBJECT WFM-NOAO-N )  #Patterns to seach in the mastersof. Be careful it needs to be in the right order. The patterns are output of the Python program seetype.py
#numsof=7 #Check this


#a=`echo ${patterns[*]/%/.*} | rev | cut -c 3- | rev`
a=0002 #Exposure to process. 
> $filesof
for i in `ls PIXTABLE*$a*.fits`
do 
	echo `readlink -f $i` PIXTABLE_OBJECT >> $filesof
done



# Using all the cal from the program or download online for this science verification run
#echo $ESOREX_OUTPUT_DIR/LSF_PROFILE.fits LSF_PROFILE >> $filesof #Also have one from the calibration
echo $CALIB_FILES/lsf_profile_slow_wfm-n.fits LSF_PROFILE   >> $filesof
echo $CALIB_FILES/std_response_wfm-n.fits STD_RESPONSE   >> $filesof
echo $CALIB_FILES/astrometry_wcs_wfm_comm2b.fits ASTROMETRY_WCS   >> $filesof
echo $CALIB_FILES/sky_lines.fits SKY_LINES   >> $filesof
echo $CALIB_FILES/extinct_table.fits EXTINCT_TABLE   >> $filesof
echo $CALIB_FILES/filter_list.fits FILTER_LIST   >> $filesof

taskset -c 0-23 esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof
