#!/bin/bash

#It creates the sof for the master flat and then execute the command to create a master flat
#It needs the MASTER_BIAS.fits and BADPIXEL table optional. 

#Source params file
source /home/detoeuf/Manuel/scripts/2014-08-02/config/params

#cd $DATA_LOCATION
cd $ESOREX_OUTPUT_DIR

#Variables
recipe=muse_flat
patterns=(FLAT WFM-NOAO-N muocal)  #Patterns to seach in the mastersof. Be careful it needs to be in the right order. The patterns are output of the Python program seetype.py
#inputs=(MASTER_BIAS BADPIX_TABLE) #The input files for the recipe. 
filesof=flat.sof
numsof=5


a=`echo ${patterns[*]/%/.*} | rev | cut -c 3- | rev`
> $filesof
cat mastersof.txt | grep -E "$a" | head -n $numsof > $filesof 
echo $ESOREX_OUTPUT_DIR/MASTER_BIAS.fits MASTER_BIAS >> $filesof 
echo $CALIB_FILES/badpix_table.fits BADPIX_TABLE >> $filesof 
#Do it with input list and search in both master and products and calibration 

taskset -c 0-23 esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof

#Update products sof with product frames
echo $ESOREX_OUTPUT_DIR/MASTER_FLAT.fits MASTER_FLAT >> productsof.txt
echo $ESOREX_OUTPUT_DIR/TRACE_TABLE.fits TRACE_TABLE >> productsof.txt
