#!/bin/bash

#Souce Params file with enviroment variables
scripts=/home/detoeuf/Manuel/scripts/2014-08-01
source $scripts/config/params 

cd $DATA_LOCATION


#Variables
recipe=muse_standard
filesof=standard.sof
#patterns=(OBJECT WFM-NOAO-N )  #Patterns to seach in the mastersof. Be careful it needs to be in the right order. The patterns are output of the Python program seetype.py
#numsof=7 


#a=`echo ${patterns[*]/%/.*} | rev | cut -c 3- | rev`
a=0001 #Exposure to process. 
> $filesof
for i in `ls PIXTABLE_STD*$a*.fits`
do 
	echo `readlink -f $i` PIXTABLE_STD >> $filesof
done



# Using all the cal from the program or download online for this science verification run
echo $CALIB_FILES/extinct_table.fits EXTINCT_TABLE   >> $filesof
echo $CALIB_FILES/std_flux_table.fits STD_FLUX_TABLE >> $filesof
echo $CALIB_FILES/filter_list.fits FILTER_LIST   >> $filesof




export ESOREX_LOG_FILE=${0##*/}
taskset -c 0-23 /home/detoeuf/muse1.2.1/bin/esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof

#Create list of product files to productsof.txt
product=(DATACUBE_STD_$a.fits)
for i in "${product[@]}"
do
	if [ -f $i ]; 
	then 
		grep $i productsof.txt > /dev/null 
		if [ $? -eq 0 ];
		then 
			sed -i "/$i/c\\$ESOREX_OUTPUT_DIR/$i `stat -c %y $i`" productsof.txt
		else
			echo $ESOREX_OUTPUT_DIR/$i `stat -c %y $i` >> productsof.txt
		fi
	else
		echo $i " Has not been created yet" >> productsof.txt 
	fi
done
#Update product in script
cp productsof.txt $scripts/products/
cp $filesof $scripts/products/
cp $ESOREX_LOG_DIR/$ESOREX_LOG_FILE $scripts/products/
