#!/bin/bash


#It creates a set-of-frames (sof) to use the muse_bias routine from /home/detoeuf/muse1.2.1/bin/esorex 
#and create a master bias

#Souce Params file with enviroment variables
scripts=/home/detoeuf/Manuel/scripts/combine2014-07-27and2014-07-28
source $scripts/config/params 




#Variables
exposure=CenterExposure
recipe=muse_exp_align
filesof=align.sof
initexp=1
endexp=8 # This is the number of expo of the same region


DATA_LOCATION=$DATA_LOCATION/$exposure
ESOREX_OUTPUT_DIR=$ESOREX_OUTPUT_DIR/$exposure
ESOREX_LOG_DIR=$ESOREX_OUTPUT_DIR/logs


#Change to data location
cd $DATA_LOCATION

> $filesof
for i in `ls *IMAGE*.fits`
do
	        echo `readlink -f $i` IMAGE_FOV >> $filesof
	done


#Call to /home/detoeuf/muse1.2.1/bin/esorex
export ESOREX_LOG_FILE=${0##*/}
taskset -c 0-23 $HOME/muse1.2.1/bin/esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof 


test -f productsof.txt || touch productsof.txt   # Test if it does exist

#Create list of product files to productsof.txt
product=(OFFSET_LIST.fits)
for i in "${product[@]}"
do
	if [ -f $i ]; 
	then 
		grep $i productsof.txt > /dev/null 
		if [ $? -eq 0 ];
		then 
			sed -i "/$i/c\\$ESOREX_OUTPUT_DIR/$i `stat -c %y $i`" productsof.txt
		else
			echo $ESOREX_OUTPUT_DIR/$i `stat -c %y $i` >> productsof.txt
		fi
	else
		echo $i " Has not been created yet" >> productsof.txt 
	fi
done
#Update product in script
cp productsof.txt $scripts/products/
cp $filesof $scripts/products/
cp $ESOREX_LOG_DIR/$ESOREX_LOG_FILE $scripts/products/
