#!/usr/bin/bash

#ESOREX
export ESOREX_OUTPUT_DIR=/mnt/data/MUSE/autocombine
export ESOREX_LOG_DIR=$ESOREX_OUTPUT_DIR/logs
export ESOREX_CONFIG=/home/detoeuf/Manuel/scripts/autocombine/config/esorex.rc

#Recipecongif files
export RECIPE_CONFIG=/home/detoeuf/Manuel/scripts/autocombine/config

#Calibration files
export CALIB_FILES=$ESOREX_OUTPUT_DIR/cal

#OMP
export OMP_NUM_THREADS=24

#Data Location
export DATA_LOCATION=/mnt/data/MUSE
