#!/bin/bash

#It created sof for the flat and then execute the command to create a master flat.
#It needs the MASTER_BIAS.fits

export MASTERFLATDIR=/home/detoeuf/Manuel/data/2014-08-02


cat mastersof.txt | grep FLAT >> flat.sof 


OMP_NUM_THREADS=24 esorex --config=/home/detoeuf/Manuel/data/2014-08-02/esorex.rc  \
 --output-dir=$MASTERFLATDIR muse_flat --nifu=-1 --merge flat.sof


