#!/bin/bash
line=badpix_table.fits

#for i in `ls *`; do sed -i "/$line/s/^/#/" $i; done
#Can use other delimeter
#for i in `ls createt*`; do echo $i ; sed  -i "\#esore#s#esorex#$HOME/musepipeline1.2.1/bin/esorex#" $i ; done

