#!/bin/bash

#Souce Params file with enviroment variables
scripts=/home/detoeuf/Manuel/scripts/2014-07-27
source $scripts/config/params 

cd $DATA_LOCATION


#Variables
recipe=muse_scipost
filesof=scipost.sof
#patterns=(OBJECT WFM-NOAO-N )  #Patterns to seach in the mastersof. Be careful it needs to be in the right order. The patterns are output of the Python program seetype.py
#numsof=7 


#a=`echo ${patterns[*]/%/.*} | rev | cut -c 3- | rev`
a=0001 #Exposure to process OBJECt
stdexp=0001 #In case there are several exposures of STD processed. 
> $filesof
for i in `ls PIXTABLE_OBJECT*$a*.fits`
do 
	echo `readlink -f $i` PIXTABLE_OBJECT >> $filesof
done



# Using all the cal from the program or download online for this science verification run
#echo $ESOREX_OUTPUT_DIR/LSF_PROFILE.fits LSF_PROFILE >> $filesof #Also have one from the calibration
echo $CALIB_FILES/lsf_profile_slow_wfm-n.fits LSF_PROFILE   >> $filesof # The one made by the ESORex recipe with data. 
echo $CALIB_FILES/astrometry_wcs_wfm_comm2b.fits ASTROMETRY_WCS   >> $filesof
echo $CALIB_FILES/sky_lines.fits SKY_LINES   >> $filesof
echo $CALIB_FILES/extinct_table.fits EXTINCT_TABLE   >> $filesof
echo $CALIB_FILES/filter_list.fits FILTER_LIST   >> $filesof
# STD can be from calibration or from Data
#echo $CALIB_FILES/std_response_wfm-n.fits STD_RESPONSE   >> $filesof #Calibration
echo $ESOREX_OUTPUT_DIR/STD_RESPONSE_$stdexp.fits STD_RESPONSE >> $filesof
echo $ESOREX_OUTPUT_DIR/STD_TELLURIC_$stdexp.fits STD_TELLURIC >> $filesof




export ESOREX_LOG_FILE=${0##*/}
taskset -c 0-23 /home/detoeuf/muse1.2.1/bin/esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof

#Create list of product files to productsof.txt
product=(DATACUBE_FINAL.fits)
for i in "${product[@]}"
do
	if [ -f $i ]; 
	then 
		grep $i productsof.txt > /dev/null 
		if [ $? -eq 0 ];
		then 
			sed -i "/$i/c\\$ESOREX_OUTPUT_DIR/$i `stat -c %y $i`" productsof.txt
		else
			echo $ESOREX_OUTPUT_DIR/$i `stat -c %y $i` >> productsof.txt
		fi
	else
		echo $i " Has not been created yet" >> productsof.txt 
	fi
done
#Update product in script
cp productsof.txt $scripts/products/
cp $filesof $scripts/products/
