#!/bin/bash

#It creates the sof for the master wavecal
# then execute the command to do the wavelenght calibrationa. Need to create filearc using the python script arc.py. 


#Source params file
scripts=/home/detoeuf/Manuel/scripts/2014-07-27
source $scripts/config/params

cd $DATA_LOCATION

#Creates the list of arcs that the python program needs
patterns=(ARC WFM-NOAO-N )  #Patterns to seach in the mastersof. Be careful it needs to be in the right order. The patterns are output of the Python program seetype.py
a=`echo ${patterns[*]/%/.*} | rev | cut -c 3- | rev`
> arctodos.txt
cat cleanmastersof.txt | grep -Ew "$a"  > arctodos.txt

#Call to Python program that get the lamp number for the list of arcs in the file arctodos created above. 
python /home/detoeuf/Manuel/scripts/2014-07-27/executables/arc.py


#Variables
recipe=muse_wavecal
filesof=wavecal.sof
numsof=5

> $filesof 
cat filearc.txt | grep '#3' | head -n $numsof   > $filesof
cat filearc.txt | grep '#4' | head -n $numsof  >> $filesof
cat filearc.txt | grep '#5' | head -n $numsof  >> $filesof
echo $ESOREX_OUTPUT_DIR/MASTER_FLAT.fits MASTER_FLAT >> $filesof
echo $ESOREX_OUTPUT_DIR/MASTER_BIAS.fits MASTER_BIAS >> $filesof
echo $ESOREX_OUTPUT_DIR/TRACE_TABLE.fits TRACE_TABLE >> $filesof
echo $CALIB_FILES/line_catalog.fits LINE_CATALOG >> $filesof
echo $CALIB_FILES/badpix_table.fits BADPIX_TABLE >> $filesof

taskset -c 0-23 /home/detoeuf/musepipeline1.2.1/bin/esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof

#Create list of product files to productsof.txt
product=(WAVECAL_TABLE.fits ARC_RED.fits WAVECAL_RESIDUALS.fits)
for i in "${product[@]}"
do
	if [ -f $i ]; 
	then 
		grep $i productsof.txt > /dev/null 
		if [ $? -eq 0 ];
		then 
			sed -i "/$i/c\\$ESOREX_OUTPUT_DIR/$i `stat -c %y $i`" productsof.txt
		else
			echo $ESOREX_OUTPUT_DIR/$i `stat -c %y $i` >> productsof.txt
		fi
	else
		echo $i " Has not been created yet" >> productsof.txt 
	fi
done
#Update product in script
cp productsof.txt $scripts/products/
cp $filesof $scripts/products/
