#!/bin/bash

#It creates the sof for the master flat and then execute the command to create a master flat
#It needs the MASTER_BIAS.fits and BADPIXEL table optional. 

#Souce Params file with enviroment variables
scripts=/home/detoeuf/Manuel/scripts/2014-07-27
source $scripts/config/params 

#cd $DATA_LOCATION
cd $ESOREX_OUTPUT_DIR

#Variables
recipe=muse_flat
filesof=flat.sof
patterns=(FLAT WFM-NOAO-N Calibrations SCI1.0)  
#Patterns to seach in the mastersof. Be careful it needs to be in the right order. 
#The patterns are output of the Python program seetype.py
#inputs=(MASTER_BIAS BADPIX_TABLE) #The input files for the recipe. 
numsof=11  #Like the BIAS the selection above should give me 11 files. 


a=`echo ${patterns[*]/%/.*} | rev | cut -c 3- | rev`
> $filesof
cat cleanmastersof.txt | grep -Ew "$a" | head -n $numsof > $filesof 
echo $ESOREX_OUTPUT_DIR/MASTER_BIAS.fits MASTER_BIAS >> $filesof 
echo $CALIB_FILES/badpix_table.fits BADPIX_TABLE >> $filesof 
#Do it with input list and search in both master and products and calibration 

taskset -c 0-23 /home/detoeuf/musepipeline1.2.1/bin/esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof

#Create list of product files to productsof.txt
product=(MASTER_FLAT.fits TRACE_TABLE.fits)
for i in "${product[@]}"
do
	if [ -f $i ]; 
	then 
		grep $i productsof.txt > /dev/null 
		if [ $? -eq 0 ];
		then 
			sed  -i "/$i/c\\$ESOREX_OUTPUT_DIR/$i `stat -c %y $i`" productsof.txt
		else
			echo $ESOREX_OUTPUT_DIR/$i `stat -c %y $i` >> productsof.txt
		fi
	else
		echo $i " Has not been created yet" >> productsof.txt 
	fi
done
#Update product in script
cp productsof.txt $scripts/products/
cp $filesof $scripts/products/
