#!/bin/bash

#It needs the Wavelength, MASTER_BIAS.fits, TRACE_TABLE and LINE_CATALOG, MASTER FLAT and BAD PIXel table.  

export MASTERWAVECALDIR=/mnt/data/MUSE/2014-08-02
cd $MASTERWAVECALDIR

DPixel table from science verification as said appendix in Muse manual
echo /mnt/data/MUSE/2014-08-02/cal/cal/badpix_table_2014-09-17.fits BADPIX_TABLE >> lsf.sof


cat mastersof.txt | grep ARC >> lsf.sof 
# LINE_CATALOG from the calibration
echo /mnt/data/MUSE/2014-08-02/cal/calmuse/line_catalog.fits LINE_CATALOG >> wavecal.sof


OMP_NUM_THREADS=24 
taskset -c 0-10 esorex --config=/home/detoeuf/Manuel/scripts/2014-08-02/esorex2014-08-02.rc  \
 --output-dir=$MASTERWAVECALDIR  muse_wavecal --resample --residuals --nifu=-1 --merge wavecal.sof

