#!/bin/bash

export MASTERWAVECALDIR=/mnt/data/MUSE/2014-08-02
cd $MASTERWAVECALDIR

#cat mastersof.txt | grep ARC >> wavecal.sof 
cat mastersof.txt | grep ARC | head -10 > wavecal.sof

# LINE_CATALOG from the calibration
echo /mnt/data/MUSE/2014-08-02/cal/calmuse/line_catalog.fits LINE_CATALOG >> wavecal.sof
echo $MASTERWAVECALDIR/MASTER_BIAS.fits MASTER_BIAS >> wavecal.sof
echo $MASTERWAVECALDIR/TRACE_TABLE.fits TRACE_TABLE >> wavecal.sof
echo $MASTERWAVECALDIR/MASTER_FLAT.fits MASTER_FLAT >> wavecal.sof


export OMP_NUM_THREADS=24 
taskset -c 0-23 esorex --config=/home/detoeuf/Manuel/scripts/2014-08-02/esorex2014-08-02.rc  \
 --output-dir=$MASTERWAVECALDIR  muse_wavecal --resample --residuals --nifu=-1 --merge wavecal.sof

