#!/bin/bash

#It creates the sof for the master flat and then execute the command to create a master flat from the preflatMASTER_FLAT.fits
#It needs the MASTER_BIAS.fits and BADPIXEL table optional. 

export MASTERFLATDIR=/mnt/data/MUSE/2014-08-02
cd $MASTERFLATDIR

> flat.sof
for i in `ls preflat*.sof`;
do
echo $MASTERFLATDIR/$i'MASTER_FLAT.fits' FLAT >> flat.sof
done

# BADPixel table from science verification as said appendix in Muse manual
echo $MASTERFLATDIR/cal/cal/badpix_table_2014-09-17.fits BADPIX_TABLE >> flat.sof
echo $MASTERFLATDIR/MASTER_BIAS.fits MASTER_BIAS >> flat.sof

OMP_NUM_THREADS=24 
taskset -c 0-23 esorex --config=/home/detoeuf/Manuel/scripts/2014-08-02/esorex2014-08-02.rc  \
 --output-dir=$MASTERFLATDIR muse_flat --nifu=-1 --merge flat.sof

#Remove temp Flats:
ls *.fits | grep preflat | xargs -d '\n' rm
