#!/bin/bash

#Create mastersof. This is not use in the routines we need the "clean" one with just one set of data and one ILLUM close to the data. 
#bash createmastersof
##
####create BIAS
#bash createbiasmaster
###
####create FLATS
#bash createflatmaster
###
####create ARC
#bash createwavecal
###
####create lsf
#bash createlsf

#create twilight
#bash createtwilight

##create pixelobjects
bash createscibasicobject

##Create std object
bash createscibasicstd


##Create standard STD response
bash createstandard

##create Cube
bash createscipostcombine



