#!/bin/bash

#Souce Params file with enviroment variables
scripts=/home/detoeuf/Manuel/scripts/2014-07-28
source $scripts/config/params 

cd $DATA_LOCATION


#Variables
recipe=muse_twilight
filesof=twilight.sof
patterns=(SKYFLAT WFM-NOAO-N )  #Patterns to seach in the mastersof. Be careful it needs to be in the right order. The patterns are output of the Python program seetype.py
numsof=5 #Cant work with 7. 


a=`echo ${patterns[*]/%/.*} | rev | cut -c 3- | rev`
cat cleanmastersof.txt | grep -Ew "$a" | head -n $numsof > $filesof
cat cleanmastersof.txt | grep ILLUM >> $filesof

echo $ESOREX_OUTPUT_DIR/MASTER_BIAS.fits MASTER_BIAS >> $filesof
echo $ESOREX_OUTPUT_DIR/MASTER_FLAT.fits MASTER_FLAT >> $filesof
echo $CALIB_FILES/badpix_table.fits BADPIX_TABLE >> $filesof
echo $ESOREX_OUTPUT_DIR/TRACE_TABLE.fits TRACE_TABLE >> $filesof
echo $ESOREX_OUTPUT_DIR/WAVECAL_TABLE.fits WAVECAL_TABLE >> $filesof
echo $CALIB_FILES/geometry_table_wfm_comm2b.fits GEOMETRY_TABLE >> $filesof
echo $CALIB_FILES/vignetting_mask.fits VIGNETTING_MASK >> $filesof


taskset -c 0-23 esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof

#Create list of product files to productsof.txt
product=(TWILIGHT_CUBE.fits)
for i in "${product[@]}"
do
	if [ -f $i ]; 
	then 
		grep $i productsof.txt > /dev/null 
		if [ $? -eq 0 ];
		then 
			sed -i "/$i/c\\$ESOREX_OUTPUT_DIR/$i `stat -c %y $i`" productsof.txt
		else
			echo $ESOREX_OUTPUT_DIR/$i `stat -c %y $i` >> productsof.txt
		fi
	else
		echo $i " Has not been created yet" >> productsof.txt 
	fi
done
#Update product in script
cp productsof.txt $scripts/products/
cp $filesof $scripts/products/
