#!/bin/bash

#Souce Params file with enviroment variables
scripts=/home/detoeuf/Manuel/scripts/2014-07-31
source $scripts/config/params 


cd $DATA_LOCATION


#Variables
recipe=muse_scipost
stdexp=0001 #In case there are several exposures of STD processed. 
expnum="$(echo `ls PIXTABLE_OBJECT_* | wc -l`"/24" | bc)" #Create a DATACUBE for each exposure
for i in $(eval echo "{5..$expnum}")
do
	echo $i
	filesof=scipost$i.sof
	> $filesof
	for l in `ls PIXTABLE_OBJECT_*0$i-*.fits`
	do 
		echo `readlink -f $l` PIXTABLE_OBJECT >> $filesof
	done

# Using all the cal from the program or download online for this science verification run
echo $ESOREX_OUTPUT_DIR/LSF_PROFILE.fits LSF_PROFILE >> $filesof #Also have one from the calibration
#echo $CALIB_FILES/lsf_profile_slow_wfm-n.fits LSF_PROFILE   >> $filesof # The one made by the ESORex recipe with data. 
echo $CALIB_FILES/astrometry_wcs_wfm_comm2b.fits ASTROMETRY_WCS   >> $filesof
echo $CALIB_FILES/sky_lines.fits SKY_LINES   >> $filesof
echo $CALIB_FILES/extinct_table.fits EXTINCT_TABLE   >> $filesof
echo $CALIB_FILES/filter_list.fits FILTER_LIST   >> $filesof
# STD can be from calibration or from Data
#echo $CALIB_FILES/std_response_wfm-n.fits STD_RESPONSE   >> $filesof #Calibration
echo $ESOREX_OUTPUT_DIR/STD_RESPONSE_$stdexp.fits STD_RESPONSE >> $filesof
echo $ESOREX_OUTPUT_DIR/STD_TELLURIC_$stdexp.fits STD_TELLURIC >> $filesof


export ESOREX_LOG_FILE=${0##*/}
taskset -c 0-23 /home/detoeuf/muse1.2.1/bin/esorex --recipe-config=$RECIPE_CONFIG/$recipe'.rc' $recipe $filesof



##Change the name of the products. The number of products depend on the option muse.muse_scipost.save= . The default is cube,skymodel and produces 9 fits including a DATACUBE.

#for flag cube. It is the default
mv DATACUBE_FINAL.fits DATACUBE_FINAL_EXP0$i.fits

#for flags combined, positioned and individual
mv PIXTABLE_COMBINED.fits PIXTABLE_COMBINED_EXP0$i.fits
mv PIXTABLE_POSITIONED_0001.fits PIXTABLE_POSITIONED_0001_EXP0$i.fits
mv PIXTABLE_REDUCED_0001.fits  PIXTABLE_REDUCED_0001_EXP0$i.fits

#For default creation og skymodel
mv SKY_SPECTRUM_0001.fits SKY_SPECTRUM_0001_EXP0$i.fits
mv SKY_MASK_0001.fits SKY_MASK_0001_EXP0$i.fits
mv SKY_LINES_0001.fits SKY_LINES_0001_EXP0$i.fits
mv SKY_CONTINUUM_0001.fits SKY_CONTINUUM_0001_EXP0$i.fits

for j in `ls IMAGE_FOV_*`
do 
	newname=$(echo $j | cut -d "." -f1)
	mv $j EXP0$i$newname".fits"
done


#Create list of product files to productsof.txt
product=(DATACUBE_FINAL_EXP0$i.fits)
for h in "${product[@]}"
do
	if [ -f $h ]; 
	then 
		grep $h productsof.txt > /dev/null 
		if [ $? -eq 0 ];
		then 
			sed -i "/$h/c\\$ESOREX_OUTPUT_DIR/$h `stat -c %y $h`" productsof.txt
		else
			echo $ESOREX_OUTPUT_DIR/$h `stat -c %y $h` >> productsof.txt
		fi
	else
		echo $h " Has not been created yet" >> productsof.txt 
	fi
done
#Update product in script
cp productsof.txt $scripts/products/
cp $filesof $scripts/products/

done
cp $ESOREX_LOG_DIR/$ESOREX_LOG_FILE $scripts/products/
